apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/rhtap-perf-test/libecpg-fedora-test-fork?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/cancel-in-progress: "true"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "push" && target_branch
      == "main"
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: jhutar-1-app-rmrbk
    appstudio.openshift.io/component: libecpg-fedora-test-fork-abecb
    pipelines.appstudio.openshift.io/type: build
  name: libecpg-fedora-test-fork-abecb-on-push
  namespace: jhutar-1-tenant
spec:
  params:
    - name: package-name
      value: libecpg
    - name: git-url
      value: "{{ source_url }}"
    - name: revision
      value: "{{ revision }}"
    - name: target-branch
      value: "{{ target_branch }}"
    - name: ociStorage
      value: "quay.io/konflux-fedora/$(context.taskRun.namespace)/libecpg-fedora-test-fork-abecb:$(params.revision)"
  pipelineRef:
    name: build-fedora-package
  taskRunTemplate:
    serviceAccountName: build-pipeline-libecpg-fedora-test-fork-abecb
  workspaces:
    - name: workspace
      volumeClaimTemplate:
        metadata:
          creationTimestamp: null
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
        status: {}
    - name: git-auth
      secret:
        secretName: '{{ git_auth_secret }}'
